# Generated by Django 5.1.7 on 2025-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0005_alter_consultation_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
